### ISSUE TITLE
Animations seem to bypass custom shaders

### ISSUE THREAD

**Issue by barbiefan** [r0-zero/picom#24]
### Platform
Manjaro

### GPU, drivers, and screen setup
Nvidia rtx 3060 530.41.03-13, one monitor 3440x1440 144hz
<details>
    <summary>glxinfo -B</summary>

```
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 12288 MB
    Total available memory: 12288 MB
    Currently available dedicated video memory: 9850 MB
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: NVIDIA GeForce RTX 3060/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 530.41.03
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6.0 NVIDIA 530.41.03
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)

OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 530.41.03
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```
</details>

### Environment
i3-gaps

### picom version
vgit-e9834

<details>
<summary>Diagnostics</summary>

```
**Version:** vgit-e9834

### Extensions:

* Shape: Yes
* RandR: Yes
* Present: Present

### Misc:

* Use Overlay: Yes
* Config file used: /home/obey/.config/picom.conf

### Drivers (inaccurate):

NVIDIA

### Backend: glx

* Driver vendors:
 * GLX: NVIDIA Corporation
 * GL: NVIDIA Corporation
* GL renderer: NVIDIA GeForce RTX 3060/PCIe/SSE2

### Backend: egl

* Driver vendors:
 * EGL: NVIDIA
 * GL: NVIDIA Corporation
* GL renderer: NVIDIA GeForce RTX 3060/PCIe/SSE2
```
</details>

### Configuration:
<details>
    <summary>Configuration file</summary>

```config
backend = "glx";
glx-no-stencil = true;
glx-copy-from-front = false;
glx-no-rebind-pixmap = true;
use-damage = false;
shadow = true;
shadow-radius = 40;
shadow-offset-x = -40;
shadow-offset-y = -40;
shadow-opacity = 1;
shadow-exclude = [
    "! name~=''",
    "name = 'Plank'",
    "name = 'Docky'",
    "name = 'xfce4-notifyd'",
    "name *= 'compton'",
    "name *= 'picom'",
    "class_g = 'Kupfer'",
    "class_g = 'Synapse'",
    "class_g = 'Polybar'",
    "class_g = 'polybar'",
    "class_g ?= 'Notify-osd'",
    "class_g ?= 'Cairo-dock'",
    "_NET_WM_STATE@:32a *= '_NET_WM_STATE_HIDDEN'",
    "role = 'xborder'",
    "!I3_FLOATING_WINDOW@:c = 1"
];
shadow-ignore-shaped = false;
inactive-opacity = 0.9999999999999999;
active-opacity = 0.9999999999999999;
inactive-opacity-override = true;
inactive-dim = 0;
blur:
{
    method = "dual_kawase";
    strength = 10;
}
blur-background = true;
blur-background-frame = false;
blur-background-fixed = false;
blur-background-exclude = [
    "window_type = 'desktop'",
    "role = 'xborder'",
    "name *= 'slop'"
];
fading = false;
fade-delta = 10;
fade-in-step = 0.03;
fade-out-step = 0.03;
fade-exclude = [ ];
mark-wmwin-focused = true;
mark-ovredir-focused = true;
use-ewmh-active-win = true;
detect-rounded-corners = true;
detect-client-opacity = true;
vsync = false;
dbe = true;
unredir-if-possible = true;
focus-exclude = [ "class_g = 'Cairo-clock'", "role = 'xborder'", "name *= 'vlc'", "name *= 'mpv'"];
detect-transient = true;
detect-client-leader = true;
wintypes : 
{
  tooltip : 
  {
    fade = true;
    shadow = false;
    opacity = 0.85;
    focus = true;
  };
  fullscreen : 
  {
    fade = true;
    shadow = false;
    opacity = 1;
    focus = true;
  };
};
xrender-sync-fence = true;
window-shader-fg-rule = [
    "/home/obey/.config/picom-shaders/picom-shader.glsl: ! name *= 'slop' && ! _NET_WM_STATE@[*]:a = '_NET_WM_STATE_FULLSCREEN'",
];
animations = true;
animation-stiffness-in-tag = 125;
animation-stiffness-tag-change = 90.0;
animation-window-mass = 0.4;
animation-dampening = 15;
animation-clamping = true;
animation-for-open-window = "zoom";
animation-for-unmap-window = "squeeze";
animation-for-transient-window = "slide-down"; 
animation-for-prev-tag = "slide-left";
enable-fading-prev-tag = true;
animation-for-next-tag = "slide-right";
enable-fading-next-tag = true;
```
</details>

<details>
    <summary>Shader</summary>  

```glsl
in vec2 texcoord;
uniform sampler2D tex;
uniform float opacity;

const float min_alpha = 0.7;
const float upper_bound = 0.18;
const vec3 border_color = vec3(0.0, 1.0, 0.0);
vec2 texsize = textureSize(tex, 0);

vec4 default_post_processing(vec4 c);

vec4 window_shader() {
    vec4 color = texelFetch(tex, ivec2(texcoord), 0);
    
    if (opacity == 1.0) {
        float pixel_brightness = (color.r + color.g + color.b) / 3;
        color.a = mix(min_alpha, 1, pixel_brightness / upper_bound );
    }

    return default_post_processing(color);
}
```
</details>

### Steps of reproduction

1. Run picom from generalanimation branch with specified config and shader
2. Observe dark, non transparent window, like browser with black image open, while moving it or resizing

### Expected behavior
This non transparent window should be made transparent by shader based on colors inside (eg. black - 70% opaque, slightly grey - 80% opaque and so on)

### Current Behavior
While animations are applied (like when moving or resizing) it seems like shader is bypassed, transparency isn't there  
If window is transparent, like Alacritty in my case, transparency isn't lost. So some shader is still running, just not mine I guess...  
(video below)

### Other details

https://github.com/FT-Labs/picom/assets/74291618/bf737f3e-efd3-48d2-9f24-280414a1b991

**Comment by r0-zero** [comment]
Hmm, this seems weird. It could be because of the flickering thing I have tried to stop. I will take a look into this, but I have no idea  of why this is happening. Since it is not an error, it will be hard to track.

**Comment by r0-zero** [comment]
This should be fixed now if the shader properties are correct

**Comment by ikz87** [comment]
Seems like this issue is still not fixed


I have a shader that makes my focused window have the window border change colors overtime


If I make this window float and just drag it the shader is completely ignored

https://github.com/FT-Labs/picom/assets/98569017/d8a2340b-3ddb-4e6d-88f2-0f4f171e5d16

I'm applying the shader this way:
```
window-shader-fg-rule = [
 "/home/kz87/Code/picom-shaders/Artistic/OldCRT.glsl:class_g = 'sm64ex'",
 "/home/kz87/Code/picom-shaders/Artistic/window_borders.glsl:focused",
 #"/home/kz87/Code/picom-shaders/Artistic/bloom.glsl:name *= 'Polybar'",
 #"/home/kz87/Code/picom-shaders/Artistic/window_borders.glsl:name *= 'Eww'",
];

```

**Comment by r0-zero** [comment]
Could you send me your shaders?

**Comment by ikz87** [comment]
``` glsl
#version 330
in vec2 texcoord;             // texture coordinate of the fragment

uniform float opacity;        // opacity of the window (0.0 - 1.0)
uniform float corner_radius;  // corner radius of the window (pixels)
// doesnt work for me:
uniform float border_width;   // estimated border width of the window (pixels)
uniform sampler2D tex;        // texture of the window
uniform float time;           // time in milliseconds, counting from an unspecified starting point

// Define tweakable variables
vec4 border_color = vec4(0.73, 1.00, 0.83, 1.0);

// Default window post-processing:
// 1) invert color
// 2) opacity / transparency
// 3) max-brightness clamping
// 4) rounded corners
vec4 default_post_processing(vec4 c);

// get window size
ivec2 window_size = textureSize(tex, 0);

// Define useful functios
bool corner(bool left, bool top, float cx, float cy) {
    return (
        ((left   && texcoord.x < cx) || (!left && texcoord.x > cx))
        && ((top && texcoord.y < cy) || (!top  && texcoord.y > cy))
        && pow(cx-texcoord.x, 2)
            + pow(cy-texcoord.y, 2) 
            > pow(corner_radius-border_width, 2)
    );
}
// use this to rotate the color of the boders (2 versions with different looks)
// source: https://gist.github.com/mairod/a75e7b44f68110e1576d77419d608786
vec3 hue_shift(vec3 color, float hue) {
    const vec3 k = vec3(0.57735, 0.57735, 0.57735);
    float cosAngle = cos(hue);
    return vec3(color * cosAngle + cross(k, color) * sin(hue) + k * dot(k, color) * (1.0 - cosAngle));
}
vec3 hue_shift2(vec3 color, float dhue) {
	float s = sin(dhue);
	float c = cos(dhue);
	return (color * c) + (color * s) * mat3(
		vec3(0.167444, 0.329213, -0.496657),
		vec3(-0.327948, 0.035669, 0.292279),
		vec3(1.250268, -1.047561, -0.202707)
	) + dot(vec3(0.299, 0.587, 0.114), color) * (1.0 - c);
}
// Default window shader:
// 1) fetch the specified pixel
// 2) apply default post-processing
vec4 window_shader() {
    vec4 c = texelFetch(tex, ivec2(texcoord), 0);
    // Apply default_post_processing before doing any changes
    // to "paint" over the original window border
    c = default_post_processing(c);

    if ( c.a > 0 && (
        // borders
        texcoord.x < border_width
        || texcoord.y < border_width
        || texcoord.x > window_size.x - border_width
        || texcoord.y > window_size.y - border_width
        // rounded corners
        || corner(true,  true,  corner_radius,               corner_radius)
        || corner(false, true,  window_size.x-corner_radius, corner_radius)
        || corner(false, false, window_size.x-corner_radius, window_size.y-corner_radius)
        || corner(true,  false, corner_radius,               window_size.y-corner_radius)
    )) 
        // c = border_color;
        // use this instead for rotating hue of the border
        c.rgb = hue_shift(
            border_color.rgb,
            6.28318*float(int(time) % 10000)/10000
        );
    return c;
}
```
That's the shader shown in the video, but the issue still persists when using any of the shaders in this [repo](https://github.com/ikz87/picom-shaders)

**Comment by r0-zero** [comment]
Quick question,

I'm trying this on yshui/picom and it seems that all windows border color changes over time. Not just the focused one, is this correct?

**Comment by ikz87** [comment]
Depends on how you're applying the window shader.
If you do it at the end of the config with
```
window-shader-fg-rule = [
 "<path_to_shader>:focused",
];
```
It should only apply to the focused window

However if you instead do it with
```
window-shader-fg = "<path_to_shader>";
```
It will apply to all windows

**Comment by r0-zero** [comment]
Could you please try the latest commit?

**Comment by ikz87** [comment]
I can confirm, shaders are working correctly now, thank you :)
